### ISSUE TITLE
Add contracts to Defender through SDK

### ISSUE THREAD

**Issue by Ramarti** [OpenZeppelin/defender-sdk#205]
It seems that there is no POST/ method for contracts in the SDK docs.
https://www.api-docs.defender.openzeppelin.com/#defender-sdk-admin

Not sure if this is a doc issue or a missing endpoint, but it would be really useful to add the contracts programatically.

Thanks!

**Comment by MCarlomagno** [comment]
Hi @Ramarti there is a way:

```js
  const client = new Defender(creds);
  const contract = await client.proposal.addContract({
    contractName: 'Test',
    contractPath: 'contracts/Test.sol',
    network: 'sepolia',
  });
```
