### ISSUE TITLE
npm上发布的是空包

### ISSUE THREAD

**Issue by emberfarkas** [OpenZeppelin/defender-sdk#366]
![5323fa9d-212e-4d5c-b8e1-6d5ee7ebcb38](https://github.com/OpenZeppelin/defender-sdk/assets/29178515/042d9ea4-6893-487e-890e-0a9bee8e1e80)

**Comment by abdelaziz-mahdy** [comment]
i am having the same problem  `Error: Cannot find module '/usr/src/app/node_modules/@openzeppelin/defender-sdk-base-client/lib/index.js'. Please verify that the package.json has a valid "main" entry`

**Comment by william-il** [comment]
the defender-sdk-deploy-client/node_modules is also missing the lib

**Comment by MCarlomagno** [comment]
Hi! Thanks for reporting, the issue was fixed in `1.13.3`, please use latest version.
https://www.npmjs.com/package/@openzeppelin/defender-sdk
