### ISSUE TITLE
1.13.2 of @openzeppelin/defender-sdk-base-client missing /lib

### ISSUE THREAD

**Issue by dannliuu** [OpenZeppelin/defender-sdk#367]
Breaks some builds.

**Comment by dannliuu** [comment]
https://www.npmjs.com/package/@openzeppelin/defender-sdk-base-client/v/1.13.2?activeTab=code

**Comment by 0xSunshine** [comment]
@dannliuu you can temp fix with

```json
  "overrides": {
    "@openzeppelin/hardhat-upgrades": {
      "@openzeppelin/defender-sdk-base-client": "1.13.1",
      "@openzeppelin/defender-sdk-deploy-client": "1.13.1",
      "@openzeppelin/defender-sdk-network-client": "1.13.1"
    }
  }
  ```

**Comment by MCarlomagno** [comment]
@dannliuu Hi! We are working on fixing this issue ASAP. In the meantime, I think @0xSunshine recommendation should work, thanks for reporting!

**Comment by nuno-add3** [comment]
same here

**Comment by 0xSunshine** [comment]
> @dannliuu Hi! We are working on fixing this issue ASAP. In the meantime, I think @0xSunshine recommendation should work, thanks for reporting!

thanks, is there an eta for new build?

**Comment by Skitzzy** [comment]
I'm still having this issue for `defender-sdk-monitor-client` - have tried the temp fix suggested by @0xSunshine for this but it doesn't seem to work here 

code: 'MODULE_NOT_FOUND',
path: '/node_modules/@openzeppelin/defender-sdk/node_modules/@openzeppelin/defender-sdk-monitor-client/package.json',
requestPath: '@openzeppelin/defender-sdk-monitor-client'

**Comment by Skitzzy** [comment]
have tried deleting node_modules and reinstalling everything, still presents the same error

my package.json if it helps:

`{
  "dependencies": {
    "@openzeppelin/defender-admin-client": "1.54.4",
    "@openzeppelin/defender-autotask-client": "1.54.4",
    "@openzeppelin/defender-autotask-utils": "1.54.4",
    "@openzeppelin/defender-kvstore-client": "1.54.5",
    "@openzeppelin/defender-relay-client": "1.54.4",
    "@openzeppelin/defender-sdk": "1.13.1",
    "@openzeppelin/defender-sentinel-client": "1.54.4",
    "axios": "^1.4.0",
    "axios-retry": "3.5.0",
    "ethers": "5.5.3",
    "graphql": "^15.5.1",
    "graphql-request": "3.4.0"
  },
  "scripts": {
    "start": "node defender/index.js"
  },
  "overrides": {
    "@openzeppelin/hardhat-upgrades": {
      "@openzeppelin/defender-sdk-base-client": "1.13.1",
      "@openzeppelin/defender-sdk-deploy-client": "1.13.1",
      "@openzeppelin/defender-sdk-network-client": "1.13.1"
    }
  }
}
`

**Comment by jarethuk** [comment]
If you are using pnpm, you will need to add this instead. If using turbo repo or similar, make sure you use to top most package.json.

```
  "pnpm": {
    "overrides": {
      "@openzeppelin/defender-sdk-base-client": "1.13.1",
      "@openzeppelin/defender-sdk-deploy-client": "1.13.1",
      "@openzeppelin/defender-sdk-monitor-client": "1.13.1",
      "@openzeppelin/defender-sdk-network-client": "1.13.1"
    }
  }
```

**Comment by Skitzzy** [comment]
thank you, this worked with pnpm. I had to also upgrade my ethers to v6 which is annoying, and is also different to [the version installed by default in defender actions](https://docs.openzeppelin.com/defender/v2/module/actions#environment)

**Comment by MCarlomagno** [comment]
Hi There! We just fixed the issue in our latest release, thanks for reporting
